package base

const (
	ServerURL           = "ServerURL"
	Username            = "Username"
	Password            = "Password"
	ProxyURL            = "ProxyURL"
	ProxyUsername       = "ProxyUsername"
	ProxyPassword       = "ProxyPassword"
	Brokers             = "Brokers"
	CheckpointDir       = "CheckpointDir"
	CheckpointNamespace = "CheckpointNamespace"
	CheckpointKey       = "CheckpointKey"
	CheckpointTopic     = "CheckpointTopic"
	CheckpointPartition = "CheckpointPartition"
	ConsumerGroup       = "ConsumerGroup"
	Topic               = "Topic"
	Partition           = "Partition"
	Key                 = "Key"
	RequireAcks         = "RequiredAcks"
	FlushFrequency      = "FlushFreqency"
	SyncWrite           = "SyncWrite"
	Host                = "Host"
	HostRegex           = "Host_regex"
	Index               = "Index"
	Source              = "Source"
	Sourcetype          = "Sourcetype"
)
