package base

const (
	ServerURL           = "ServerURL"
	Username            = "Username"
	Password            = "Password"
	ProxyURL            = "ProxyURL"
	ProxyUsername       = "ProxyUsername"
	ProxyPassword       = "ProxyPassword"
	Brokers             = "Brokers"
	CheckpointDir       = "CheckpointDir"
	CheckpointNamespace = "CheckpointNamespace"
	CheckpointKey       = "CheckpointKey"
	CheckpointTopic     = "CheckpointTopic"
	CheckpointPartition = "CheckpointPartition"
	ConsumerGroup       = "ConsumerGroup"
	Topic               = "Topic"
	Partition           = "Partition"
	Key                 = "Key"
	RequireAcks         = "RequiredAcks"
	FlushFrequency      = "FlushFreqency"
	SyncWrite           = "SyncWrite"
	Host                = "Host"
	HostRegex           = "Host_regex"
	Index               = "Index"
	Source              = "Source"
	Sourcetype          = "Sourcetype"
	Platform            = "Platform"
	App                 = "App"
	Taskname            = "Taskname"
	Timestamp           = "Timestamp"
	CpuCount            = "CpuCount"
	MemAlloc            = "MemAlloc"
	TotoalMemAlloc      = "TotalMemAlloc"
	SysMemAlloc         = "SysMemAlloc"
	UseOffsetOldest     = "UseOffsetOldest"
	TaskConfig          = "_TaskConfig_"
	TaskConfigKey       = "_TaskConfigKey_"
	TaskConfigAction    = "_TaskConfigAction_"
	TaskConfigNew       = "_TaskConfigNew_"
	TaskConfigDelete    = "_TaskConfigDelete_"
	TaskConfigUpdate    = "_TaskConfigUpdate_"
	Tasks               = "_Tasks_"
	TaskStats           = "_TaskStats_"
)
